### ISSUE TITLE
Duplicate authorization requests allowed to same and multiple people

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#161] opened 2024-09-23 19:57 UTC
This may be a bug and it may be a feature request.  The system allows me to make the same authorization request over and over again.   Can be done to the same person or multiple people.  If the same person - it does show up in their Auth Queue to approve both requests.  Approving one of them does NOT remove both of them - this was confirmed in testing.   Unsure what happens when the same  request is sent to multiple people - but expect that all or some or none could approve it.   Easy way to check how much attention your authorizers are paying - send a request to all of them and see who denies it and who approves it  *evil grin*.    However - this loophole should probably not be in the system.

**Comment by sueflay** [comment] 2024-09-23 19:59
Screenshot of multiple/duplicate requests in auth request queue 

![image](https://github.com/user-attachments/assets/69647468-5cbb-4e46-8edc-307bd2d0206d)

**Comment by jhandel** [comment] 2024-09-23 20:08
This is kind of by design.  If someone does not respond we want to let the member submit again (and again, and again) until they get an answer... 

Logically how it works is each request is its own request.. but once approved, each following approval will just expire the previous approval... You could "hunt" for an approval for sure... but this has been how the system has historically worked.

Will review with stakeholders to see if we need to change this behavior.

**Comment by Chrisincr** [comment] 2024-10-30 16:11
resolved by PR #229

**Closed** 2024-11-26 02:00 UTC
Labels: enhancement, web
